# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GscCli < Formula
  desc "Google Search Console CLI"
  homepage "https://github.com/jpreagan/gsc-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpreagan/gsc-cli/releases/download/v0.1.0/gsc-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "1827823015809845b3ce0f781f1fc1f4d347c1f189f4f358a3aca703a34a276b"

      def install
        bin.install "gsc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpreagan/gsc-cli/releases/download/v0.1.0/gsc-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "61a26faed97382ef6574758eed8197f4fd598fd753cf73a68bfc99e73d3737b4"

      def install
        bin.install "gsc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpreagan/gsc-cli/releases/download/v0.1.0/gsc-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "9755d773d6534459c89068ba21a0183f22c4918f72d2e43af51d78e4c7022259"
      def install
        bin.install "gsc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpreagan/gsc-cli/releases/download/v0.1.0/gsc-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "05faf9c1664339763820f936b6a62faa311c9f20f32bd384457806426794cf08"
      def install
        bin.install "gsc"
      end
    end
  end

  test do
    system "#{bin}/gsc", "--version"
  end
end
