# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imsgctl < Formula
  desc "Portable CLI for querying imsgkit message data"
  homepage "https://github.com/jpreagan/imsgkit"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpreagan/imsgkit/releases/download/imsgctl%2Fv0.2.0/imsgctl_0.2.0_darwin_amd64.tar.gz"
      sha256 "764d4f27d1113e7ac15ec93152de2aae0e4168edca12828c34b927a9bfd6b098"

      define_method(:install) do
        bin.install "imsgctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpreagan/imsgkit/releases/download/imsgctl%2Fv0.2.0/imsgctl_0.2.0_darwin_arm64.tar.gz"
      sha256 "272260cea3926a31927afa18c9994df574911464705704b8b20d824979fd1888"

      define_method(:install) do
        bin.install "imsgctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpreagan/imsgkit/releases/download/imsgctl%2Fv0.2.0/imsgctl_0.2.0_linux_amd64.tar.gz"
      sha256 "4b4ab40bf33a935385a46cd9530c51e2b515002ca894c995a4d1ea24eed5d47d"
      define_method(:install) do
        bin.install "imsgctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpreagan/imsgkit/releases/download/imsgctl%2Fv0.2.0/imsgctl_0.2.0_linux_arm64.tar.gz"
      sha256 "f29c8e74248aa20abeb79b622d4c6477d25ececded72ff028b6fada24cce58f0"
      define_method(:install) do
        bin.install "imsgctl"
      end
    end
  end
end
