# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imsgctl < Formula
  desc "Portable CLI for querying imsgkit message data"
  homepage "https://github.com/jpreagan/imsgkit"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpreagan/imsgkit/releases/download/imsgctl%2Fv0.3.0/imsgctl_0.3.0_darwin_amd64.tar.gz"
      sha256 "42876853b973c13e16260be9b2cfd8ff97704f5ec0ac3ca83889209a0b5ff72a"

      define_method(:install) do
        bin.install "imsgctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpreagan/imsgkit/releases/download/imsgctl%2Fv0.3.0/imsgctl_0.3.0_darwin_arm64.tar.gz"
      sha256 "42a4d8eaef7fa60a788d06b650f289223a6c5361add3d4cfcc306fa312401fa8"

      define_method(:install) do
        bin.install "imsgctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpreagan/imsgkit/releases/download/imsgctl%2Fv0.3.0/imsgctl_0.3.0_linux_amd64.tar.gz"
      sha256 "c3b5f2c4e2c1ef29903d3860be23754042b122c65557ef8839ec5e87a81ebdc3"
      define_method(:install) do
        bin.install "imsgctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpreagan/imsgkit/releases/download/imsgctl%2Fv0.3.0/imsgctl_0.3.0_linux_arm64.tar.gz"
      sha256 "a2af6591678587de800776e9c7eb49216d904ec9fa715ab66d67c6b4842f024c"
      define_method(:install) do
        bin.install "imsgctl"
      end
    end
  end
end
